# Generated by Django 3.1.7 on 2021-04-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeInTimeOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Quadralogix', 'Quadralogix'), ('Getaka Labs', 'Getaka Labs')], max_length=255)),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
            ],
        ),
    ]
