# Generated by Django 3.1.7 on 2021-04-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210404_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeintimeout',
            name='time_in',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='timeintimeout',
            name='time_out',
            field=models.TimeField(blank=True),
        ),
    ]
