# Generated by Django 3.1.7 on 2021-04-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210404_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeintimeout',
            name='category',
            field=models.CharField(choices=[('Quadralogix', 'Quadralogix'), ('Getaka Labs', 'Getaka Labs')], max_length=255),
        ),
    ]
