# Generated by Django 3.1.7 on 2021-04-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_timeintimeout_total_hrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeintimeout',
            name='total_hrs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
