# Generated by Django 3.1.7 on 2021-04-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210404_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeintimeout',
            name='total_hrs',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
