# Generated by Django 3.1.7 on 2021-04-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210404_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeintimeout',
            name='break_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeintimeout',
            name='break_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
