# Generated by Django 3.1.7 on 2021-04-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_timeintimeout_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeintimeout',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
