# Generated by Django 3.1.7 on 2021-04-04 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210404_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeintimeout',
            name='shift_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
