# Generated by Django 3.1.7 on 2021-04-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_timeintimeout_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeintimeout',
            name='task',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
